// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1D3PPJ0Y-CTWUYg35k8ssLi5rKPtsiA',
    appId: '1:985225477081:web:f4943c1457bdb2088eb7c8',
    messagingSenderId: '985225477081',
    projectId: 'minerestoran',
    authDomain: 'minerestoran.firebaseapp.com',
    storageBucket: 'minerestoran.appspot.com',
    measurementId: 'G-NRG8T8VNQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-mwm01PiiA7aJKRUSU4TOVw2U8ObijaY',
    appId: '1:985225477081:android:99554983a82ed5528eb7c8',
    messagingSenderId: '985225477081',
    projectId: 'minerestoran',
    storageBucket: 'minerestoran.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC02dD1Bt8iV9bC7S08R3mHXE0tG_qI-oE',
    appId: '1:985225477081:ios:98984a5dca5fde958eb7c8',
    messagingSenderId: '985225477081',
    projectId: 'minerestoran',
    storageBucket: 'minerestoran.appspot.com',
    iosBundleId: 'com.example.minerestoran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC02dD1Bt8iV9bC7S08R3mHXE0tG_qI-oE',
    appId: '1:985225477081:ios:575220901f9d35708eb7c8',
    messagingSenderId: '985225477081',
    projectId: 'minerestoran',
    storageBucket: 'minerestoran.appspot.com',
    iosBundleId: 'com.example.minerestoran.RunnerTests',
  );
}
